version: '3'
networks:
  openhim:

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
    networks:
      - openhim
    healthcheck:
     test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3
    volumes:
     - /etc/letsencrypt/live/openhim.swisstph-mis.ch/fullchain.pem:/etc/letsencrypt/live/openhim.swisstph-mis.ch/fullchain.pem
     - /etc/letsencrypt/live/openhim.swisstph-mis.ch/privkey.pem:/etc/letsencrypt/live/openhim.swisstph-mis.ch/privkey.pem
     - /home/ubuntu/openfn-openhim-mediator/openhim-core-conf/default.json:/usr/src/app/config/default.json
     - /home/ubuntu/openfn-openhim-mediator/openhim-core-conf/development.json:/usr/src/app/config/development.json

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "9000:443"
    healthcheck:
     test: "curl -sS http://openhim-console || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3
    volumes:
      - /home/ubuntu/openfn-openhim-mediator/network/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/openfn-openhim-mediator/network/console.app.default.json:/usr/share/nginx/html/config/default.json
      - /etc/letsencrypt/live/openhim.swisstph-mis.ch/fullchain.pem:/etc/letsencrypt/live/openhim.swisstph-mis.ch/fullchain.pem
      - /etc/letsencrypt/live/openhim.swisstph-mis.ch/privkey.pem:/etc/letsencrypt/live/openhim.swisstph-mis.ch/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
  mediator-somalia:
     container_name: mediator-somalia
     restart: unless-stopped
     networks:
       - openhim
     expose:
       - "4000"
     build: ../
     environment:
       - OPENHIM_URL=https://openhim-core:8080
       - TRUST_SELF_SIGNED=true
       - OPENHIM_USERNAME=httu.admin@swisstph.ch
       - OPENHIM_PASSWORD=xWlUg5Gl1fAyYEG2QeAx
       - SERVER_PORT=4000
       - CONTAINER_NAME=mediator-somalia
       - MEDIATOR_NAME=Mediator Somalia
       - MEDIATOR_URN=urn:mediator:skeleton-production-mediator-somalia
       - MEDIATOR_DESCRIPTION=Mediator somalia
       - URL_PATTERN=^/somaliaEndpoint
       - ROUTE_NAME=Somalia production route
  mediator-sysref-reg:
     container_name: mediator-sysref-reg
     restart: unless-stopped
     networks:
       - openhim
     expose:
       - "4002"
     build: ../
     environment:
       - OPENHIM_URL=https://openhim-core:8080
       - TRUST_SELF_SIGNED=true
       - OPENHIM_USERNAME=httu.admin@swisstph.ch
       - OPENHIM_PASSWORD=xWlUg5Gl1fAyYEG2QeAx
       - SERVER_PORT=4002
       - CONTAINER_NAME=mediator-sysref-reg
       - MEDIATOR_NAME=mediator-sysref-reg
       - MEDIATOR_URN=urn:mediator:production-mediator-sysref-reg
       - MEDIATOR_DESCRIPTION=Mediator for Sysref registration project
       - URL_PATTERN=^/sysrefRegEndpoint
       - ROUTE_NAME=Sysref registration production route
  mediator-sysref:
     container_name: mediator-sysref
     restart: unless-stopped
     networks:
       - openhim
     expose:
       - "4001"
     build: ../
     environment:
       - OPENHIM_URL=https://openhim-core:8080
       - TRUST_SELF_SIGNED=true
       - OPENHIM_USER=root@openhim.org
       - OPENHIM_PASSWORD=password
       - SERVER_PORT=4001
       - CONTAINER_NAME=mediator-sysref
       - MEDIATOR_NAME=Skeleton Production Bootstrap Mediator Sysref
       - MEDIATOR_URN=urn:mediator:skeleton-production-mediator-sysref
       - MEDIATOR_DESCRIPTION=Mediator Sysref
       - URL_PATTERN=^/sysrefEndpoint
       - ROUTE_NAME=Sysref production route
  mediator-cht:
     container_name: mediator-cht
     restart: unless-stopped
     networks:
       - openhim
     expose:
       - "4003"
     build: ../
     environment:
       - OPENHIM_URL=https://openhim-core:8080
       - TRUST_SELF_SIGNED=true
       - OPENHIM_USER=root@openhim.org
       - OPENHIM_PASSWORD=password
       - SERVER_PORT=4003
       - CONTAINER_NAME=mediator-cht
       - MEDIATOR_NAME=Skeleton Production Bootstrap Mediator CHT
       - MEDIATOR_URN=urn:mediator:skeleton-production-mediator-cht
       - MEDIATOR_DESCRIPTION=Mediator CHT
       - URL_PATTERN=^/chtEndpoint
       - ROUTE_NAME=CHT production route

volumes:
  mongo-data:
