version: '3'
networks:
  openhim:
services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
    ports:
      - "8080:8080"
      - "5001:5001"
      - "5000:5000"
    networks:
      - openhim
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /etc/letsencrypt/live/YOUR-HOST/fullchain.pem:/etc/letsencrypt/live/YOUR-HOST/fullchain.pem
      - /etc/letsencrypt/live/YOUR-HOST/privkey.pem:/etc/letsencrypt/live/YOUR-HOST/privkey.pem
      - /home/ubuntu/openfn-openhim-mediator/openhim-core-conf/default.json:/usr/src/app/config/default.json
      - /home/ubuntu/openfn-openhim-mediator/openhim-core-conf/development.json:/usr/src/app/config/development.json
  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "9000:443"
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json
      - /etc/letsencrypt/live/YOUR-HOST/fullchain.pem:/etc/letsencrypt/live/YOUR-HOST/fullchain.pem
      - /etc/letsencrypt/live/YOUR-HOST/privkey.pem:/etc/letsencrypt/live/YOUR-HOST/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - /etc/nginx/sites-available/default:/etc/nginx/sites-available/default
      - /etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
      - /home/ubuntu/openfn-openhim-mediator/default.conf:/etc/nginx/conf.d/default.conf
  mediator:
    container_name: mediator
    restart: unless-stopped
    networks:
      - openhim
    expose:
      - "4321"
    build: ../
    environment:
      - OPENHIM_URL=https://openhim-core:8080
      - TRUST_SELF_SIGNED=true
      - OPENHIM_PASSWORD=password
      - SERVER_PORT=4321

volumes:
  mongo-data:
